%YAML:1.0
visualization:
  direct_conversion: true
  clahe:
    clip_limit: 3.0
    tile_grid_size: 4

stream:
  color:
    width: 640
    height: 480
    format: "BGR8"
    fps: 30
  depth:
    width: 640
    height: 480
    format: "Z16"
    fps: 30

depth_range:
  min: 0.1
  max: 3.0

save:
  directory: "./results/"