%YAML:1.0
visualization:
  direct_conversion: true
  clahe:
    clip_limit: 3.0
    tile_grid_size: 4

stream:
  color:
    width: 640
    height: 480
    format: "BGR8"
    fps: 30
  depth:
    width: 640
    height: 480
    format: "Z16"
    fps: 30

depth_range:
  min: 0.1
  max: 3.0

save:
  directory: "./results/"

# 포즈 추정 설정
pose:
  model_path: "./trt/higher_hrnet.trt" # .trt 모델 파일 경로
  use_cuda: true                       # CUDA 사용 여부 (TensorRT 사용 시 true여야 함)
  confidence_threshold: 0.3            # 키포인트 신뢰도 임계값
  input_width: 512                     # 모델 입력 너비
  input_height: 512                    # 모델 입력 높이
  heatmap_width: 128                   # 히트맵 너비
  heatmap_height: 128                  # 히트맵 높이
  preprocess:
    mean: [0.485, 0.456, 0.406]       # 정규화 평균 (BGR 순서 아님, 코드에서 BGR로 사용) - 주의: OpenCV BGR 순서 유의
    std: [0.229, 0.224, 0.225]        # 정규화 표준편차 (BGR 순서 아님, 코드에서 BGR로 사용) - 주의: OpenCV BGR 순서 유의